"""add player image_url

Revision ID: 8bafe9e8cc58
Revises: 242119ee3849
Create Date: 2026-07-22 16:00:31.836649
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8bafe9e8cc58'
down_revision: Union[str, None] = '242119ee3849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('image_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'image_url')
    # ### end Alembic commands ###
