"""add player youth-value columns

Revision ID: c8e2e60fd6e7
Revises: f774a9b1290a
Create Date: 2026-07-16 10:59:06.751200
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c8e2e60fd6e7'
down_revision: Union[str, None] = 'f774a9b1290a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('international_caps', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('international_goals', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('contract_expiration', sa.Date(), nullable=True))
    op.add_column('players', sa.Column('highest_market_value_eur', sa.Numeric(precision=14, scale=0), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'highest_market_value_eur')
    op.drop_column('players', 'contract_expiration')
    op.drop_column('players', 'international_goals')
    op.drop_column('players', 'international_caps')
    # ### end Alembic commands ###
