"""initial normalized schema

Revision ID: dec8abb87c1c
Revises: 
Create Date: 2026-07-15 10:17:03.815567
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'dec8abb87c1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('normalized_name', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('transfermarkt_id', sa.Integer(), nullable=True),
    sa.Column('understat_id', sa.Integer(), nullable=True),
    sa.Column('fbref_name', sa.String(length=128), nullable=True),
    sa.Column('clubelo_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', 'country', name='uq_club_name_country')
    )
    op.create_index(op.f('ix_clubs_clubelo_name'), 'clubs', ['clubelo_name'], unique=False)
    op.create_index(op.f('ix_clubs_name'), 'clubs', ['name'], unique=False)
    op.create_index(op.f('ix_clubs_normalized_name'), 'clubs', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_clubs_transfermarkt_id'), 'clubs', ['transfermarkt_id'], unique=False)
    op.create_index(op.f('ix_clubs_understat_id'), 'clubs', ['understat_id'], unique=False)
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('transfermarkt_code', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_code'), 'leagues', ['code'], unique=True)
    op.create_index(op.f('ix_leagues_transfermarkt_code'), 'leagues', ['transfermarkt_code'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('normalized_name', sa.String(length=160), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=64), nullable=True),
    sa.Column('primary_position', sa.String(length=16), nullable=True),
    sa.Column('foot', sa.String(length=8), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_birth_year'), 'players', ['birth_year'], unique=False)
    op.create_index(op.f('ix_players_full_name'), 'players', ['full_name'], unique=False)
    op.create_index(op.f('ix_players_normalized_name'), 'players', ['normalized_name'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_code'), 'seasons', ['code'], unique=False)
    op.create_index(op.f('ix_seasons_label'), 'seasons', ['label'], unique=True)
    op.create_index(op.f('ix_seasons_start_year'), 'seasons', ['start_year'], unique=False)
    op.create_table('club_strength',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('clubelo_name', sa.String(length=128), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('elo', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=16), nullable=True),
    sa.Column('league_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clubelo_name', 'snapshot_date', name='uq_elo_name_date')
    )
    op.create_index(op.f('ix_club_strength_club_id'), 'club_strength', ['club_id'], unique=False)
    op.create_index(op.f('ix_club_strength_clubelo_name'), 'club_strength', ['clubelo_name'], unique=False)
    op.create_index(op.f('ix_club_strength_snapshot_date'), 'club_strength', ['snapshot_date'], unique=False)
    op.create_table('entity_xref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('source_key', sa.String(length=256), nullable=True),
    sa.Column('match_method', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('fbref', 'understat', 'transfermarkt', 'clubelo', 'statsbomb')", name='ck_xref_source'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', 'source_key', name='uq_xref_source_identity')
    )
    op.create_index(op.f('ix_entity_xref_player_id'), 'entity_xref', ['player_id'], unique=False)
    op.create_index(op.f('ix_entity_xref_source'), 'entity_xref', ['source'], unique=False)
    op.create_index(op.f('ix_entity_xref_source_id'), 'entity_xref', ['source_id'], unique=False)
    op.create_index(op.f('ix_entity_xref_source_key'), 'entity_xref', ['source_key'], unique=False)
    op.create_table('market_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('value_eur', sa.Numeric(precision=14, scale=0), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'as_of', name='uq_mv_player_date')
    )
    op.create_index(op.f('ix_market_values_as_of'), 'market_values', ['as_of'], unique=False)
    op.create_index(op.f('ix_market_values_player_id'), 'market_values', ['player_id'], unique=False)
    op.create_table('player_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('matches', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Float(), nullable=True),
    sa.Column('assists', sa.Float(), nullable=True),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('xa', sa.Float(), nullable=True),
    sa.Column('position', sa.String(length=16), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('fbref', 'understat', 'transfermarkt', 'clubelo', 'statsbomb')", name='ck_pss_source'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season_id', 'club_id', 'source', name='uq_pss_player_season_club_source')
    )
    op.create_index(op.f('ix_player_season_stats_club_id'), 'player_season_stats', ['club_id'], unique=False)
    op.create_index(op.f('ix_player_season_stats_league_id'), 'player_season_stats', ['league_id'], unique=False)
    op.create_index(op.f('ix_player_season_stats_player_id'), 'player_season_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_season_stats_season_id'), 'player_season_stats', ['season_id'], unique=False)
    op.create_index(op.f('ix_player_season_stats_source'), 'player_season_stats', ['source'], unique=False)
    op.create_table('team_tactical_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'season_id', name='uq_ttp_club_season')
    )
    op.create_index(op.f('ix_team_tactical_profiles_club_id'), 'team_tactical_profiles', ['club_id'], unique=False)
    op.create_index(op.f('ix_team_tactical_profiles_season_id'), 'team_tactical_profiles', ['season_id'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=True),
    sa.Column('season_label', sa.String(length=16), nullable=True),
    sa.Column('from_club_id', sa.Integer(), nullable=True),
    sa.Column('to_club_id', sa.Integer(), nullable=True),
    sa.Column('fee_eur', sa.Numeric(precision=14, scale=0), nullable=True),
    sa.Column('market_value_eur', sa.Numeric(precision=14, scale=0), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['to_club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_player_id'), 'transfers', ['player_id'], unique=False)
    op.create_index(op.f('ix_transfers_transfer_date'), 'transfers', ['transfer_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfers_transfer_date'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_player_id'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_team_tactical_profiles_season_id'), table_name='team_tactical_profiles')
    op.drop_index(op.f('ix_team_tactical_profiles_club_id'), table_name='team_tactical_profiles')
    op.drop_table('team_tactical_profiles')
    op.drop_index(op.f('ix_player_season_stats_source'), table_name='player_season_stats')
    op.drop_index(op.f('ix_player_season_stats_season_id'), table_name='player_season_stats')
    op.drop_index(op.f('ix_player_season_stats_player_id'), table_name='player_season_stats')
    op.drop_index(op.f('ix_player_season_stats_league_id'), table_name='player_season_stats')
    op.drop_index(op.f('ix_player_season_stats_club_id'), table_name='player_season_stats')
    op.drop_table('player_season_stats')
    op.drop_index(op.f('ix_market_values_player_id'), table_name='market_values')
    op.drop_index(op.f('ix_market_values_as_of'), table_name='market_values')
    op.drop_table('market_values')
    op.drop_index(op.f('ix_entity_xref_source_key'), table_name='entity_xref')
    op.drop_index(op.f('ix_entity_xref_source_id'), table_name='entity_xref')
    op.drop_index(op.f('ix_entity_xref_source'), table_name='entity_xref')
    op.drop_index(op.f('ix_entity_xref_player_id'), table_name='entity_xref')
    op.drop_table('entity_xref')
    op.drop_index(op.f('ix_club_strength_snapshot_date'), table_name='club_strength')
    op.drop_index(op.f('ix_club_strength_clubelo_name'), table_name='club_strength')
    op.drop_index(op.f('ix_club_strength_club_id'), table_name='club_strength')
    op.drop_table('club_strength')
    op.drop_index(op.f('ix_seasons_start_year'), table_name='seasons')
    op.drop_index(op.f('ix_seasons_label'), table_name='seasons')
    op.drop_index(op.f('ix_seasons_code'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_players_normalized_name'), table_name='players')
    op.drop_index(op.f('ix_players_full_name'), table_name='players')
    op.drop_index(op.f('ix_players_birth_year'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_leagues_transfermarkt_code'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_code'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_clubs_understat_id'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_transfermarkt_id'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_normalized_name'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_name'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_clubelo_name'), table_name='clubs')
    op.drop_table('clubs')
    # ### end Alembic commands ###
