"""widen position/foot columns

Revision ID: e14967f8d44c
Revises: dec8abb87c1c
Create Date: 2026-07-15 12:12:36.549916
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e14967f8d44c'
down_revision: Union[str, None] = 'dec8abb87c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_season_stats', 'position',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('players', 'primary_position',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('players', 'foot',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'foot',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.alter_column('players', 'primary_position',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('player_season_stats', 'position',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###
