"""add player_features table

Revision ID: f774a9b1290a
Revises: 92c70ddb0a3c
Create Date: 2026-07-15 15:35:50.787154
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f774a9b1290a'
down_revision: Union[str, None] = '92c70ddb0a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('feature_set_version', sa.String(length=16), nullable=False),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('matches', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=32), nullable=True),
    sa.Column('position_group', sa.String(length=8), nullable=True),
    sa.Column('club_elo', sa.Float(), nullable=True),
    sa.Column('league_strength', sa.Float(), nullable=True),
    sa.Column('market_value_eur', sa.Numeric(precision=14, scale=0), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season_id', 'feature_set_version', name='uq_pf_player_season_version')
    )
    op.create_index(op.f('ix_player_features_feature_set_version'), 'player_features', ['feature_set_version'], unique=False)
    op.create_index(op.f('ix_player_features_player_id'), 'player_features', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_features_position_group'), 'player_features', ['position_group'], unique=False)
    op.create_index(op.f('ix_player_features_season_id'), 'player_features', ['season_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_features_season_id'), table_name='player_features')
    op.drop_index(op.f('ix_player_features_position_group'), table_name='player_features')
    op.drop_index(op.f('ix_player_features_player_id'), table_name='player_features')
    op.drop_index(op.f('ix_player_features_feature_set_version'), table_name='player_features')
    op.drop_table('player_features')
    # ### end Alembic commands ###
